#!/bin/bash
#
# Copyright (c) 2023, Akbar Rifai.
#

touch /tmp/interfaces-refresher.lck

ifup mm

i=0
while true; do
  if [[ $(ifstatus mm | jq -r '.up') == "true" ]]; then
    break
  fi
  if [[ $i -eq 30 ]]; then
    exit 1
  fi
  if [[ $i -eq 2 ]] || [[ $i -eq 5 ]] || [[ $i -eq 10 ]] || [[ $i -eq 20 ]]; then
    ifup mm
  fi
  i=$((i+1))
  sleep 1
done

ifup wwan0

# cleanup interfaces-refresher
atq -q r | awk '{ print $1 }' | xargs atrm

# openclash reload firewall
/etc/init.d/openclash reload firewall

# openclash connections closer
function start_openclash_connections_closer() {
  file="/tmp/openclash_connections_closer.pid"
  nohup bash -c "while true; do curl 'http://192.168.1.1:9090/connections' -X DELETE -H 'Authorization: Bearer darktunnel'; done" >/dev/null 2>&1 &
  echo $! > $file
}

function stop_openclash_connections_closer() {
  file="/tmp/openclash_connections_closer.pid"
  kill -9 $(cat $file)
  rm -f $file
}

start_openclash_connections_closer
sleep 10

# wait until ip prefix is not 10. or 100.
ip_log="/tmp/interfaces-refresher-ip.log"
rm -f $ip_log
timeout=$(($(date +%s)+30))
while true; do
  stop_openclash_connections_closer
  ip=$(curl --max-time 10 icanhazip.com)
  echo $ip >> $ip_log
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    if [[ $ip != 10.* ]] && [[ $ip != 100.* ]]; then
      break
    fi
  fi
  if [[ $(date +%s) -ge $timeout ]]; then
    echo "timeout" >> $ip_log
    exit 1
  fi
  start_openclash_connections_closer
  sleep 1
done

exit 0
