#!/bin/bash
#
# Copyright (c) 2023, Akbar Rifai.
#

IF1="mm"
IF2="wwan0"

IF1_up=$(ifstatus $IF1 | jq -r '"\(.up)"')

timestamp=$(date +%s)

IF2_data=$(ifstatus $IF2 | jq -r '"\(.up) \(.uptime) \(.data.leasetime)"')
IF2_up=$(echo $IF2_data | awk '{ print $1 }')

if [[ $IF1_up == "false" ]] || [[ $IF2_up == "false" ]]; then
  if [[ ! -f /tmp/interfaces-refresher.lck ]]; then
    /root/interfaces-refresher
  fi
  exit 0
fi

rm /tmp/interfaces-refresher.lck

# check if interfaces-refresher is already added
if [[ "$(atq -q r | wc -l)" -gt 0 ]]; then
  exit 0
fi

IF2_uptime=$(echo $IF2_data | awk '{ print $2 }')
IF2_leasetime=$(echo $IF2_data | awk '{ print $3 }')

refresh_interfaces_timestamp=$((($timestamp-$IF2_uptime)+$IF2_leasetime))
refresh_interfaces_datetime=$(date -d "@$refresh_interfaces_timestamp" +"%H:%M")
delay=$(($(date -d "@$refresh_interfaces_timestamp" +"%S")-2))
delay=$(($delay > 0 ? $delay : 0))

if [[ $(($refresh_interfaces_timestamp)) -le $(date +%s) ]]; then
  /root/interfaces-refresher
  exit 0
fi

# send to at
cat << EOF | at -q r "$refresh_interfaces_datetime"
sleep $delay; /root/interfaces-refresher
EOF
