#!/bin/bash
#
# Copyright (c) 2023, Akbar Rifai.
#

touch /tmp/interfaces-refresher.lck

ifup mm

i=0
while true; do
  if [[ $(ifstatus mm | jq -r '.up') == "true" ]]; then
    break
  fi
  if [[ $i -eq 2 ]] || [[ $i -eq 5 ]] || [[ $i -eq 10 ]]; then
    ifup mm
  fi
  i=$((i+1))
  sleep 1
done

ifup wwan0

# cleanup interfaces-refresher
atq -q r | awk '{ print $1 }' | xargs atrm

exit 0
