#!/bin/bash
#
# Copyright (c) 2023, Akbar Rifai.
#

IF1="mm"
IF2="wwan0"

IF1_up=$(ifstatus $IF1 | jq -r '"\(.up)"')

IF2_data=$(ifstatus $IF2 | jq -r '"\(.up) \(.uptime) \(.data.leasetime)"')
IF2_up=$(echo $IF2_data | awk '{ print $1 }')

if [[ $IF1_up == "false" ]] || [[ $IF2_up == "false" ]]; then
  /root/interfaces-refresher
  exit 0
fi

IF2_uptime=$(echo $IF2_data | awk '{ print $2 }')
IF2_leasetime=$(echo $IF2_data | awk '{ print $3 }')

if [[ $(($IF2_leasetime-$IF2_uptime)) -le 60 ]]; then
  /root/interfaces-refresher
  exit 0
fi